
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetryinstrumentations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetryinstrumentations/finalizers
  verbs:
  - update
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetryinstrumentations/status
  verbs:
  - get
  - patch
  - update
